### PR TITLE
Update JCheung-P3-README.md

### PR DESCRIPTION
**Pull request by JaronJCheung**
Dear @ahasanzadeh13 and @Jiemingy,

You are invited to review my Project 3. Thank you for your consideration. Please let me know if you have any questions. 

Best, 
Jaron

### CODE REVIEW

**Comment by Jiemingy** [comment]
Hi Jaron, 

Good work! Clear explanation. Here are my comments:

Q1b. I just wonder if the property can be used in the possible world setting, so that a existence_end_with b in the actual world and b existence_end_with c in a possible world doesn't necessarily mean that a existence_end_with c. 

Q2 b. Also if aligned with can be used in the possible world setting. 

Q3c. In natural language, adulthood and seniorhood overlap. So the answer needs to define that they do not overlap. Am I right? 

Q4c. Similarly, if without the definition that A is not overlap S, then should add A (J, t3). 

Q7a. Just add: also see the definition of Site (p. 112). 

All other answers sound great, except for Q5 and Q8 - I have limited knowledge of these parts, so I give no comment on these answers. 

Bests,
Jieming

**Comment by ahasanzadeh13** [comment]
Hi Jaron,
If the version I looked at is your latest version, I wanted to suggest that "Object Aggregate" might not be the best solution for parts d, g, and h of question 6. 
I believe options such as site, 2D spatial region, and 3D spatial region may be better choices.

Also, the following is my answer to question 9. I believe it is more simplified:
"Imagine you have a really big puzzle that you need to solve. Instead of trying to solve the whole puzzle at once, you can solve small parts of it at a time. This makes it much easier and faster to solve the puzzle.
Similarly, when people make changes to a big computer system called an ontology, they don't want to have to solve the whole system again every time. So instead, they use a special tool called the Pellet reasoner that can solve small parts of the system at a time, only looking at the parts that have changed. This makes it much faster and easier to update the system when changes are made."

**Comment by JaronJCheung** [comment]
> Hi Jaron,
> 
> Good work! Clear explanation. Here are my comments:
> 
> Q1b. I just wonder if the property can be used in the possible world setting, so that a existence_end_with b in the actual world and b existence_end_with c in a possible world doesn't necessarily mean that a existence_end_with c.
> 
> Q2 b. Also if aligned with can be used in the possible world setting.
> 
> Q3c. In natural language, adulthood and seniorhood overlap. So the answer needs to define that they do not overlap. Am I right?
> 
> Q4c. Similarly, if without the definition that A is not overlap S, then should add A (J, t3).
> 
> Q7a. Just add: also see the definition of Site (p. 112).
> 
> All other answers sound great, except for Q5 and Q8 - I have limited knowledge of these parts, so I give no comment on these answers.
> 
> Bests, Jieming

Dear Jieming, 

Thank you for your review! I appreciate the time you took to take a look at my project. 

Q1 & Q2 RE: possible worlds: I think this is a great question and I think Beverley would be able to answer this best. Personally, I would refrain from possible world examples because applied ontology seems to work with ideas tethered to the actual world (i.e. actualism). Let's ask Professor Beverley! 

Q3 & Q4 (c): You raise a good point! I may add a distinction in those respective answers. 

Thanks and take care, 
Jaron

**Comment by JaronJCheung** [comment]
> Hi Jaron, If the version I looked at is your latest version, I wanted to suggest that "Object Aggregate" might not be the best solution for parts d, g, and h of question 6. I believe options such as site, 2D spatial region, and 3D spatial region may be better choices.
> 
> Also, the following is my answer to question 9. I believe it is more simplified: "Imagine you have a really big puzzle that you need to solve. Instead of trying to solve the whole puzzle at once, you can solve small parts of it at a time. This makes it much easier and faster to solve the puzzle. Similarly, when people make changes to a big computer system called an ontology, they don't want to have to solve the whole system again every time. So instead, they use a special tool called the Pellet reasoner that can solve small parts of the system at a time, only looking at the parts that have changed. This makes it much faster and easier to update the system when changes are made."

Dear Ali, 

Thank you for taking the time to review my Project 3! 

Q6: Yes! Thanks for checking in on this. I was able to update my answers after our group review. 

Q9: Thanks for sharing your answer! It is indeed more simplified than mine and has its advantages. Its brevity would be helpful in teaching a five year old, as children at that age have a shorter attention span (compared to their older counterparts). 

Thanks again for taking the time to review my work. 

Sincerely, 
Jaron

**Pull request merged**
