### PR TITLE
Update JCheung-P2-README.md

### PR DESCRIPTION
**Pull request by JaronJCheung**
Dear @dmcnulty27 and @giacomodecolle,

You are both invited to review my Project 2. Thanks for being willing to share your wisdom and insight with me :). 

Please let me know if you have any questions. Thanks in advance!

Best, 
Jaron

### CODE REVIEW

**Review by dmcnulty27 — COMMENTED** [review]
f

**Comment by dmcnulty27** [comment]
In regards to question 6, I think you did wonderfully. I am going to utilize your technique. I was really struggling with the vagueness of the sentences but the way you have it explained is not only helpful but in my view intuitive! I do want to ask as I have a different understanding of the curly brackets surrounding {a} in part (d). My understanding was that {a} indicates a name. Can you explain a little further how you drew your conclusions in this regard?

**Comment by dmcnulty27** [comment]
Regarding Questions 4 and 5 your answers seem very very close to an example we saw in class, just wanted to alert you to the prompt stating "each distinct from any interpretation covered in class so far." 
Just in case Dr. Beverly sees this as too close to the teaching example we have examined it may be good to have a backup! :)

**Comment by JaronJCheung** [comment]
> 

@dmcnulty27, thank you for your encouraging comment and for your patience! I am guessing that you probably already got your question answered, but I will give it a try. 

6(d): ∃r-.{a}--in first-order logic (as Karl insightfully pointed out [so grateful for him lol]) is ∀x∃y(r-(x,y)∧(y=a)), or ∀x∃y(r(y,x)∧(y=a))). In my understanding, the curly bracket represents a restricted set for which there is one individual, i.e. a. The interpretation the group came up with in natural language is: for all xs, there is element a, which is r-inverse related to it.

I think it is fine to think of a as a name, if that name refers to a particular individual. In our natural language interpretation, we called it an element, but specified it with its name, that is, "a".

Does this help? Have you learned anything new since you first asked this question?

Thanks again!

**Comment by JaronJCheung** [comment]
> Regarding Questions 4 and 5 your answers seem very very close to an example we saw in class, just wanted to alert you to the prompt stating "each distinct from any interpretation covered in class so far."
> Just in case Dr. Beverly sees this as too close to the teaching example we have examined it may be good to have a backup! :)

@dmcnulty27, thank you for this piece of feedback! When we were making our models for 4 and 5, this was a concern as well. What we did was we changed the amount of course individuals and role assignments for each. Hopefully it was enough to answer 4 and 5 sufficiently!

**Comment by dmcnulty27** [comment]
Jaron love your photos of Angels landing and Half dome two of my favorite hikes!

**Comment by JaronJCheung** [comment]
> Jaron love your photos of Angels landing and Half dome two of my favorite hikes!

Thank you! I think it's so cool that you did both hikes as well. We have to exchange stories at class! 

I appreciate and am thankful your review, comments, and insight! 

Best, 
Jaron

**Comment by dmcnulty27** [comment]
> > 
> 
> @dmcnulty27, thank you for your encouraging comment and for your patience! I am guessing that you probably already got your question answered, but I will give it a try.
> 
> 6(d): ∃r-.{a}--in first-order logic (as Karl insightfully pointed out [so grateful for him lol]) is ∀x∃y(r-(x,y)∧(y=a)), or ∀x∃y(r(y,x)∧(y=a))). In my understanding, the curly bracket represents a restricted set for which there is one individual, i.e. a. The interpretation the group came up with in natural language is: for all xs, there is element a, which is r-inverse related to it.
> 
> I think it is fine to think of a as a name, if that name refers to a particular individual. In our natural language interpretation, we called it an element, but specified it with its name, that is, "a".
> 
> Does this help? Have you learned anything new since you first asked this question?
> 
> Thanks again!

I guess I consider name to be an individual whether that be an individual element or an instance or a person. But I see your point.

**Review by giacomodecolle — APPROVED** [review]
Good job on everything Jaron, I didn't see any mistakes. For ex. 10, some of the exercises can be done by using inverse properties. E.g. say that x is a whole of y, that wholeof is inverse of parthood, and get that y is a part of x. Also I will definitely use something like your idea for the last part of exercise 10, had no idea of what "having no parts in common" could look like.

**Comment by JaronJCheung** [comment]
> Good job on everything Jaron, I didn't see any mistakes. For ex. 10, some of the exercises can be done by using inverse properties. E.g. say that x is a whole of y, that wholeof is inverse of parthood, and get that y is a part of x. Also I will definitely use something like your idea for the last part of exercise 10, had no idea of what "having no parts in common" could look like.

@giacomodecolle, thank you for the review and comments! I appreciate your time and insight. I definitely benefitted from your response on Q9. 

Thanks again! 

Best, 
Jaron

**Pull request merged**
